apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: memory-leak-simulator-dc
labels:
  template: memory-leak-simulator-dc
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: "${NAME}"
      app.kubernetes.io/component: "${NAME}"
      app.kubernetes.io/version: "${VERSION}"
    name: "${NAME}"
  spec:
    lookupPolicy:
      local: true
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: "${NAME}"
      app.kubernetes.io/component: "${NAME}"
      app.kubernetes.io/version: "${VERSION}"
    name: "${NAME}"
  spec:
    replicas: 1
    selector:
      app.kubernetes.io/component: "${NAME}"
      app.kubernetes.io/version: "${VERSION}"
    template:
      metadata:
        labels:
          app.kubernetes.io/component: "${NAME}"
          app.kubernetes.io/version: "${VERSION}"
      spec:
        containers:
          - env:
              - name: KUBERNETES_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: JAVA_OPTS_APPEND
                value: -Xms64m -XX:MaxRAMPercentage=50 
              - name: JAVA_APP_JAR
                value: /deployments/quarkus-run.jar
            resources:
              requests:
                cpu: 250m
                memory: 1Gi
              limits:
                cpu: 250m
                memory: 1Gi  
            image: ${NAME}:latest
            imagePullPolicy: Always
            name: "${NAME}"            
            ports:
              - containerPort: 8080
                name: http
                protocol: TCP
    triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
            - "${NAME}"
          from:
            kind: ImageStreamTag
            name: ${NAME}:latest
        type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: "${NAME}"
      app.kubernetes.io/component: "${NAME}"
      app.kubernetes.io/version: "${VERSION}"
    name: "${NAME}"
  spec:
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 8080
    selector:
      app.kubernetes.io/component: "${NAME}"
      app.kubernetes.io/version: "${VERSION}"
    type: ClusterIP      
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: "${NAME}"
      app.kubernetes.io/component: "${NAME}"
      app.kubernetes.io/version: "${VERSION}"
    name: "${NAME}"
  spec:
    port:
      targetPort: http
    to:
      kind: Service
      name: "${NAME}"
parameters:
- description: Name that will be given to all the resources
  displayName: Name
  name: NAME
  required: true
  value: "memory-leak-simulator"
- description: Version that will be given to all the resources
  displayName: Version
  name: VERSION
  required: true
  value: '1.0.0'